# Generated by Django 4.1.4 on 2023-06-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0002_alter_people_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='user',
        ),
    ]
