# Generated by Django 4.1.4 on 2023-06-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, to='basic_auth.people', to_field='email')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
